### PR TITLE
add Friend class

### PR DESCRIPTION
**Pull request by Ateeeeeee**
please leave some comments

### CODE REVIEW

**Review by katerynablavt — DISMISSED** [review]
good work, joe

**Review by xingjianll — CHANGES_REQUESTED** [review]
It is AddFriendInteractor not Interavtor :(

**Review by davidlyj — DISMISSED** [review]
Looks good. Green light to merge for me.

**Review by xingjianll — APPROVED** [review]
All good.

**Review by katerynablavt — APPROVED** [review]
good

**Review by davidlyj — APPROVED** [review]
Good to go. Merge please.

**Pull request merged**
