### PR TITLE
Clean architecture enhancements/implementations and refactoring

### PR DESCRIPTION
**Pull request by davidlyj**
Made RatingPresenter implement from RatingPresenterInputBoundary and extracted peerPort into and instance attribute to increase ease of future changes.

### CODE REVIEW

**Review by as39248 — APPROVED** [review]
lgtm

**Review by brendenmcfarlane — APPROVED** [review]
great!

**Review by xingjianll — APPROVED** [review]
Cool.

**Comment by xingjianll** [comment]
Branch outdated.

**Pull request closed without merging**
