### PR TITLE
Merge Feature Branch Send chat

### PR DESCRIPTION
**Pull request by xingjianll**
This is a merge pull request for my feature branch.

### CODE REVIEW

**Review by katerynablavt — APPROVED** [review]

**Review by davidlyj — DISMISSED** [review]
Looks good. Comments are useful in understanding more complex classes/methods. Those without comments are easy to understand from the code itself.

**Review by as39248 — CHANGES_REQUESTED** [review]
for the output boundary i think you forgot to add chatUid

**Review by katerynablavt — APPROVED** [review]

**Review by thmcheung — APPROVED** [review]
Impressive work!

**Review by as39248 — APPROVED** [review]
looks good

**Pull request merged**
