### PR TITLE
Merged main with my branch and pushed some changes regarding my OutputAdapter

### PR DESCRIPTION
**Pull request by davidlyj**
To avoid conflicts and to further implement clean architecture

### CODE REVIEW

**Review by xingjianll — DISMISSED** [review]
Good.

**Review by brendenmcfarlane — APPROVED** [review]
Package names loook good!

**Review by thmcheung — APPROVED** [review]
good

**Review by brendenmcfarlane — APPROVED** [review]
Looks Good! Tests finally pass again!

**Review by xingjianll — APPROVED** [review]
Cool

**Review by brendenmcfarlane — DISMISSED** [review]
This looks like a bit more than just the description of the PR, but the code still looks good. We'll need tests and documentation in the future but that can be done later since we are so close to having the functionality complete. It looks like when the last merge from main happened here the all the tests failed from the file directory being renamed, Im glad you resolved those

**Review by JoeZZG — APPROVED** [review]
checked

**Review by brendenmcfarlane — APPROVED** [review]
Looks good! Lets get this merged!

**Pull request merged**
