### PR TITLE
Feature group chat

### PR DESCRIPTION
**Pull request by brendenmcfarlane**
Updates in CreateGC usecase:
-AS PER TAS REQUEST, removed excessive docstrings (I also made variable and method names more descriptive)
-as per kevins request, refactored interactor to call output adapter once for every person in the group chat.
-minor changes to other classes such as matching new constructors
-fixed compiling and gradle errors

From initial PR:
-CreateGCController
-CreateGCOutputAdapter
-RetrieveFriendsListController
-RetrieveFriendsListOutputAdapter

To Do:
-one more test case on the interactor (mentioned in test suite)

### CODE REVIEW

**Review by xingjianll — DISMISSED** [review]
cool.

**Review by as39248 — DISMISSED** [review]
approved

**Review by as39248 — DISMISSED** [review]
lgtm

**Review by davidlyj — APPROVED** [review]
Code looks good and ready to be merged into main

**Review by JoeZZG — APPROVED** [review]
approved

**Review by thmcheung — APPROVED** [review]

**Pull request merged**
