### PR TITLE
Rating Feature Branch

### PR DESCRIPTION
**Pull request by davidlyj**
Added attributes and methods. Please review.

### CODE REVIEW

**Review by JoeZZG — APPROVED** [review]
good

**Review by brendenmcfarlane — DISMISSED** [review]
Im going to approve this, but I have some feedback that I think we should consider refactoring into this class in the future.
     I dont understand why Rating.avgRating has a setter, it just means you can override the rating to whatever you want without taking into account the other ratings before.
     Also I feel like it would make sense for Rating.calculateRating() to actually set the new average rating since it takes into account all the other ratings.
     Lastly I feel like all of the individual ratings should be stored in some kind of data structure so they can be seen individually, and this would also allow us to add other features in the future, such as allowing users to change the ratings they submitted.

**Review by thmcheung — DISMISSED** [review]
GOOD

**Review by katerynablavt — APPROVED** [review]
good

**Review by thmcheung — DISMISSED** [review]

**Review by katerynablavt — CHANGES_REQUESTED** [review]
Looks like very clear architecture haha
I'm still not sure whether fields in classes should be private and then we can reach them through getters.
Also to finish the use case layer you should add the Output adapter class that implements the output boundary.

**Review by katerynablavt — APPROVED** [review]

**Review by thmcheung — APPROVED** [review]
GOOD

**Review by xingjianll — APPROVED** [review]
Approved.

**Pull request merged**
