### PR TITLE
optimized interfaces in friend

### PR DESCRIPTION
**Pull request by JoeZZG**
changed some duplicate code

### CODE REVIEW

**Comment by davidlyj** [comment]
Checks have failed. Please expand the details to see the file where an error is thrown and make the required changes.

**Review by katerynablavt — APPROVED** [review]

**Review by brendenmcfarlane — CHANGES_REQUESTED** [review]
This PR cannot run our tests due to a compiling error, it looks like the imports need to be renamed from the last file directory renaming

**Review by davidlyj — CHANGES_REQUESTED** [review]
Autograding fails. Please expand the autograding details, make the required changes and re-commit, thank you!

**Comment by xingjianll** [comment]
This pr will be closed because all of Joe's updated code is in the feature-friend-request branch.

**Pull request closed without merging**
