### PR TITLE
Created markdown files entities.md and FrameworksAndDrivers.md

### PR DESCRIPTION
**Pull request by brendenmcfarlane**
added these folders so the rest of the directory is available for everyone

### CODE REVIEW

**Review by davidlyj — DISMISSED** [review]
Code looks good, it is ready for merging.

**Review by Ateeeeeee — APPROVED** [review]
goodgood

**Review by katerynablavt — APPROVED** [review]
yeeeah entity folders!!

**Review by xingjianll — APPROVED** [review]
Looks good.

**Review by davidlyj — APPROVED** [review]
Files look good. Code has been reviewed and ready to be merged.

**Pull request merged**
