### PR TITLE
Feature login logout register delete account

### PR DESCRIPTION
**Pull request by thmcheung**
Kevin finished the login feature and I finished the logout, register, and delete account features for the program.
The data access class extends on all the DBgateway classes and manipulates the database: user.csv to complete actions required.

Right now, the user can login, logout, register and delete. When logging in, the user retrieves all of the data from the server, and creates the corresponding data structure in the model, nothing is stored locally when the user logs out.

We've tested the features and they all work.

### CODE REVIEW

**Review by as39248 — APPROVED** [review]
lgtm

**Review by as39248 — DISMISSED** [review]
.

**Review by brendenmcfarlane — CHANGES_REQUESTED** [review]
no

**Review by xingjianll — APPROVED** [review]
Goodjob.

**Review by JoeZZG — APPROVED** [review]
checked

**Review by xingjianll — APPROVED** [review]
Good.

**Review by as39248 — APPROVED** [review]
lgtm

**Review by davidlyj — APPROVED** [review]
Some autograding tests failed but user story run-through tests from the console work great. So, I am going to approve it.

**Review by brendenmcfarlane — APPROVED** [review]
sure

**Pull request merged**
