### PR TITLE
Database

### PR DESCRIPTION
**Pull request by xingjianll**
This is probably my final implementation of the database class. To use it, create your own data access class and use the public methods to implement your methods. The database component contains the Database class which stores information in user.csv and chat.csv. It also stores information in temporary buffers `ArrayList<String[]> chatDatabase` `ArrayList<String[]> userDatabase`, and a number of changes to these two lists need to occur before the data is written into the actual files, to improve performance (currently the threshold is set to 1 so the files are always up to date). 

Please use the methods (especially `readUser()` `readChat()` `writeUser()` `writeChat()`) to implement your data access.

### CODE REVIEW

**Review by xgao28 — APPROVED** [review]
I am Marcus and I approve, I'm using my friend's computer

**Review by brendenmcfarlane — CHANGES_REQUESTED** [review]
We cannot push content to the main branch whe it cannot pass tests. I checked the test run it and there are compiling errors in the last commit made

**Review by davidlyj — CHANGES_REQUESTED** [review]
Autograding fails. Please expand the details, resolve the issues and re-commit. Thank you!

**Review by davidlyj — CHANGES_REQUESTED** [review]
Autograding checks have failed. Please make the required changes. Thank you!

**Pull request merged**
