### PR TITLE
Merge send chat feature into Main.

### PR DESCRIPTION
**Pull request by xingjianll**
This is perhaps the final version of my send chat feature with completed controllers, usecases and output adapters.

### CODE REVIEW

**Review by as39248 — APPROVED** [review]
having a constant is a really smart way to make the architecture clean

**Review by brendenmcfarlane — APPROVED** [review]
LGTM! Great idea with the separator!

**Review by thmcheung — APPROVED** [review]
good

**Comment by davidlyj** [comment]
Changes look good. However, conflicts must be resolved before approval.

**Review by brendenmcfarlane — APPROVED** [review]
Im going to approve this because it looks good, but I believe for the sake of clean architecture the send chat input/output model should have private variables. Since we have a lot of missing functionality in our program, Ive created an issue for this and you can refactor that later

**Review by davidlyj — APPROVED** [review]
Thanks for resolving the issues that led to the autograding checks being failed. Changes look good and ready to be merged.

**Comment by xingjianll** [comment]
Guys there is no need to merge this branch, too many conflicts. My code are almost all pushed anyways.

**Pull request closed without merging**
