### PR TITLE
[Feature] send message final

### PR DESCRIPTION
**Pull request by xingjianll**
In this branch I implemented the final version of my send message feature. The user is able to use $view <chatUid> to see chat, then $send <content> to send a message in the chat. Both the client side and the server side are fully implemented. When the server receives a chat message, this message is stored after cell 6 in chat.csv. All clients in the chat will be updated when this change happens. The update is stored in the model. If the client just happens to be viewing the chat, the message will appear on screen. The view implements ModelObserver and observes the model to receive updates. The model can have more than one observer.

### CODE REVIEW

**Review by JoeZZG — DISMISSED** [review]
Checked

**Review by katerynablavt — DISMISSED** [review]

**Review by as39248 — DISMISSED** [review]
lgtm

**Comment by xingjianll** [comment]
Sorry guys I pushed to my branch instead of merging it, but i resolved all conflicts.

**Review by JoeZZG — APPROVED** [review]
Checked

**Review by katerynablavt — APPROVED** [review]

**Review by as39248 — APPROVED** [review]
lgtm

**Comment by xingjianll** [comment]
NIce!

**Pull request merged**
