### PR TITLE
Added communication interfaces and Utils folder.

### PR DESCRIPTION
**Pull request by xingjianll**

### CODE REVIEW

**Review by thmcheung — APPROVED** [review]
牛逼！

**Review by katerynablavt — DISMISSED** [review]
ok

**Review by brendenmcfarlane — CHANGES_REQUESTED** [review]
Utils Package needs to be lower case in pothole_case in order for gradle to operate correctly.

**Comment by xingjianll** [comment]
Changed package name to all lowercase.

**Review by brendenmcfarlane — APPROVED** [review]
looks good now

**Comment by xingjianll** [comment]
No longer needed as files are already merged.

**Pull request closed without merging**
