### PR TITLE
Created client side packages.

### PR DESCRIPTION
**Pull request by xingjianll**
Merge newly created packages for the server side.

### CODE REVIEW

**Review by katerynablavt — DISMISSED** [review]

**Review by JoeZZG — APPROVED** [review]
nice change, viewed. no logical error

**Review by JoeZZG — APPROVED** [review]
checked

**Review by JoeZZG — APPROVED** [review]
checked, no obvious bug

**Review by thmcheung — APPROVED** [review]

**Review by as39248 — APPROVED** [review]
approved

**Comment by davidlyj** [comment]
The autograding checks failed. Please expand details to see where the error is thrown and make the required changes. Thanks!

**Review by as39248 — APPROVED** [review]
lgtm

**Review by thmcheung — DISMISSED** [review]

**Review by JoeZZG — DISMISSED** [review]
checked

**Review by JoeZZG — APPROVED** [review]
done check

**Review by katerynablavt — APPROVED** [review]
dont forget to delete gradle files from main

**Review by thmcheung — APPROVED** [review]

**Pull request merged**
